host: https://Pocleonis1.testrail.io
project: TestNG
username: testrailpoc@falltrack.net
password: Sommer2029!!
#api: 6y9DdTeLJChrtJHi0DUN-vmolkjbiXfgg9kKXI406
title: testcase
file: /Users/leonismiroci/Desktop/Lokal/report_sample/TEST-TestSuite.xml